format = """
[░▒▓](#4F9574)\
$username\
$hostname\
[ 󰣇 ](bg:#4F9574 fg:#090c0c)\
[](bg:#449351 fg:#4F9574)\
$directory\
[](fg:#449351)\
\n$character"""

[directory]
style = "fg:white bg:#449351"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"pictures" = " "
"games" = " "
"desktop" = " "

[username]
show_always = true
style_user = "bold fg:white bg:#4F9574"
style_root = "bg:#9A348E"
format = '[ $user@]($style)'
disabled = false

[hostname]
ssh_only = false
disabled = false
style = "bg:#4F9574 fg:white"
format = '[$hostname]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
