format = """
[░▒▓](#CCC1E0)\
$username\
$hostname\
[ 󰣇 ](bg:#CCC1E0 fg:#090c0c)\
[](bg:#FEC6DA fg:#CCC1E0)\
$directory\
[](fg:#FEC6DA)\
\n$character"""

[directory]
style = "fg:black bg:#FEC6DA"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"pictures" = " "
"games" = " "
"desktop" = " "

[username]
show_always = true
style_user = "fg:black bg:#CCC1E0"
style_root = "bg:#9A348E"
format = '[ $user@]($style)'
disabled = false

[hostname]
ssh_only = false
disabled = false
style = "bg:#CCC1E0 fg:black"
format = '[$hostname]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#C4B5A0"
format = '[[  $time ](fg:#E5E3E1 bg:#D3AF3A)]($style)'
