format = """
[░▒▓](#B890F3)\
$username\
$hostname\
[ 󰣇 ](bg:#B890F3 fg:#090c0c)\
[](bg:#F776C1 fg:#B890F3)\
$directory\
[](fg:#F776C1)\
\n$character"""

[directory]
style = "fg:black bg:#F776C1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"pictures" = " "
"games" = " "
"desktop" = " "

[username]
show_always = true
style_user = "fg:black bg:#B890F3"
style_root = "bg:#9A348E"
format = '[ $user@]($style)'
disabled = false

[hostname]
ssh_only = false
disabled = false
style = "bg:#B890F3 fg:black"
format = '[$hostname]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#C4B5A0"
format = '[[  $time ](fg:#E5E3E1 bg:#D3AF3A)]($style)'
