format = """
[░▒▓](#D5DCE8)\
$username\
$hostname\
[ 󰣇 ](bg:#D5DCE8 fg:#090c0c)\
[](bg:#81A1C1 fg:#D5DCE8)\
$directory\
[](fg:#81A1C1)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#81A1C1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"pictures" = " "
"games" = " "
"desktop" = " "

[username]
show_always = true
style_user = "bold fg:black bg:#D5DCE8"
style_root = "bg:#9A348E"
format = '[ $user@]($style)'
disabled = false

[hostname]
ssh_only = false
disabled = false
style = "bg:#D5DCE8 fg:black"
format = '[$hostname]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
