format = """
[░▒▓](#7FA67D)\
$username\
$hostname\
[ 󰣇 ](bg:#7FA67D fg:#090c0c)\
[](bg:#6D8DAE fg:#7FA67D)\
$directory\
[](fg:#6D8DAE)\
\n$character"""

[directory]
style = "fg:#e3e5e5 bg:#6D8DAE"
format = "[ $path ]($style)"
truncation_length = 3
#97879Ctruncation_symbol = "…/"

[directory.substitutions]
"documents" = "󰈙 "
"downloads" = " "
"music" = " "
"pictures" = " "
"games" = " "
"desktop" = " "

[username]
show_always = true
style_user = "bold fg:black bg:#7FA67D"
style_root = "bg:#9A348E"
format = '[ $user@]($style)'
disabled = false

[hostname]
ssh_only = false
disabled = false
style = "bg:#7FA67D fg:black"
format = '[$hostname]($style)'

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:#C4B5A0"
format = '[[  $time ](fg:#E5E3E1 bg:#D3AF3A)]($style)'
